import dns from 'dns'
dns.setDefaultResultOrder('ipv4first')

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
//import Footer from "@/components/shared/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dragon News App",
  description: "Generated by Dragon News App",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="max-w-300 mx-auto">
        <main>
          {children}
        </main>
        {/* <Footer/> */}
        <ToastContainer position='top-center' />
      </body>
    </html>
  );
}
